name: user_panel
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  dropdownfield: ^1.0.3
  google_maps_flutter: ^1.0.6
  connectivity: ^2.0.2
  country_code_picker: ^1.7.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
#  firebase_database: ^6.0.0
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  image_picker: ^0.6.7+22
  cached_network_image: ^2.5.0
  country_state_city_picker: ^1.2.7
  alphabet_list_scroll_view: ^1.0.6
  url_launcher: ^5.7.10
  esys_flutter_share: ^1.0.2
    #  share: ^0.6.5+4
#  http: ^0.12.2
  pie_chart: ^4.0.1
  aamarpay: ^0.0.7
  flutter_staggered_animations: ^0.1.3
  expandable_text: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dakterbari_logo.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/doctor.jpg
    - assets/logo.png
    - assets/logo_2.jpg
    - assets/male.png
    - assets/patient_apps.jpg
    - assets/dakterbariapp_logo.jpg
    - assets/doctor_patient.png
    - assets/loadingimage.gif
    - assets/home_icon/notifications.png
    #  - Home
    - assets/home_icon/appointment.png
    - assets/home_icon/blog.png
    - assets/home_icon/forum.png
    - assets/home_icon/medicine.png
    - assets/home_icon/prescription.png
    - assets/home_icon/review.png
    - assets/home_icon/support.png
    - assets/home_icon/doctor.png
    - assets/home_icon/shop.png
#    - assets/home_icon/patient_questions.jpg
    - assets/home_icon/shopping.png
    - assets/home_icon/credit_assesment.png
    - assets/home_icon/health_insurance.png
    - assets/home_icon/join_riders.png
    - assets/home_icon/account.png
    #  - Medical Category
    - assets/medical_category/coronavirus.png
    - assets/medical_category/cardiology.png
    - assets/medical_category/chest.png
    - assets/medical_category/cancer.png
    - assets/medical_category/dentist.png
    - assets/medical_category/diabetes.png
    - assets/medical_category/eye.png
    - assets/medical_category/gastroenterology.png
    - assets/medical_category/ent.png
    - assets/medical_category/gynecology.png
    - assets/medical_category/hematology.png
    - assets/medical_category/herbal.png
    - assets/medical_category/homeopathic.png
    - assets/medical_category/medicine.png
    - assets/medical_category/pain_medicine.png
    - assets/medical_category/neuro_medicine.png
    - assets/medical_category/neurosurgery.png
    - assets/medical_category/nutrition.png
    - assets/medical_category/oncology.png
    - assets/medical_category/pediatrics.png
    #- assets/medical_category/nephrology.png
    - assets/medical_category/orthopaedic.png
    - assets/medical_category/physical_medicine.png
    - assets/medical_category/physiotherapy.png
    - assets/medical_category/plastic_surgery.png
    - assets/medical_category/skin.png
    - assets/medical_category/thyroid.png
    - assets/medical_category/urology.png
    - assets/medical_category/urology_Specialist.png
    - assets/medical_category/psychiatrist.png
    - assets/medical_category/vascular_surgery.png
    # -  Social icon
    - assets/social_icon/email_48.png
    - assets/social_icon/facebook_48.png
    - assets/social_icon/globe_48.png
    - assets/social_icon/linkedin_48.png
    - assets/social_icon/phone_48.png
    - assets/social_icon/twitter_48.png
    - assets/icons/email-send100.png
    - assets/icons/facebook128.png
    - assets/icons/linkedin128.png
    - assets/icons/marker100.png
    - assets/icons/twitter128.png
    - assets/icons/youtube128.png
    - assets/icons/pinterest128.png
  #  - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
